server:
  port: 8080

#配置 前端模板引擎
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML5 #
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    appname: xiaomo_admin
    instance-id: sh_xiaomo_admin
